import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[window]
startup_mode = "FullScreen"
option_as_alt = "OnlyLeft"

[font]
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic"}
size=18

