#!/bin/zsh

mkdir -p "$HOME/.config"

# Link neovim configuration to `$HOME/.config`
rm -rf "$HOME/.config/nvim"
ln -sf "$PWD/nvim" "$HOME/.config/nvim"
echo "nvim configuration done"

# Link the tmux configuration and install the tmux plugin manager
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
echo "tmux configuration done"

# Link the kitty configuration
rm -rf "$HOME/.config/kitty"
ln -sf "$PWD/kitty" "$HOME/.config/kitty"
echo "kitty configuration done"
