if (( $+commands[kubectl] )); then
  alias k='kubectl'
  alias ka='kubectl apply'
  alias kaf='kubectl apply -f'
  alias kdel='kubectl delete'
  alias kdf='kubectl delete -f'
  alias kdes='kubectl describe'
  alias ke='kubectl exec -it'
  alias kg='kubectl get'
  alias kga='kubectl get all'
  alias kgd='kubectl get deployments'
  alias kgn='kubectl get nodes'
  alias kgp='kubectl get pods'
  alias kgpa='kubectl get pods --all-namespaces'
  alias kgs='kubectl get services'
  alias kl='kubectl logs'
  alias kctx='kubectl config current-context'
  alias kuctx='kubectl config use-context'
  alias kns='kubectl config set-context --current --namespace'
fi
