#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = hypr-start-services
exec-once = sh -c 'sleep 1; hyprctl hyprpaper wallpaper "DP-3,/home/cesar/.config/wallpaper.png"'
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = ghostty
exec-once = firefox
exec-once = signal-desktop
exec-once = cider
exec-once = sh -c 'command -v telegram-desktop >/dev/null 2>&1 && telegram-desktop'
