##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    name = opaque-ghostty
    match:class = ^(com\.mitchellh\.ghostty)$

    opacity = 1.0 override 1.0 override
}

windowrule {
    name = workspace-ghostty
    match:class = ^(com\.mitchellh\.ghostty)$

    workspace = 1
}

windowrule {
    name = workspace-browser
    match:class = ^(firefox|vivaldi-stable)$

    workspace = 2
}

windowrule {
    name = workspace-chats-signal
    match:class = ^(signal)$

    workspace = 3
}

windowrule {
    name = workspace-chats-telegram
    match:class = ^(org\.telegram\.desktop|TelegramDesktop|telegram-desktop)$

    workspace = 3
}

windowrule {
    name = workspace-cider
    match:class = ^(Cider)$

    workspace = 10
}

windowrule {
    name = float-1password
    match:class = ^(1Password)$

    float = yes
    center = yes
    size = 900 640
}

windowrule {
    name = float-pavucontrol
    match:class = ^(org\.pulseaudio\.pavucontrol)$

    float = yes
    center = yes
    size = 920 680
}

windowrule {
    name = float-file-pickers
    match:title = ^(Open File|Open Folder|Save File|Save As|Choose Files|Select a File|Select Files|Choose a File)$

    float = yes
    center = yes
    size = 1100 760
}

windowrule {
    name = float-auth-prompts
    match:title = ^(Authentication Required|Authenticate|OpenSSH Authentication Passphrase Request|Choose password for new keyring)$

    float = yes
    center = yes
}

windowrule {
    name = pip-vivaldi
    match:class = ^(vivaldi-stable)$
    match:title = ^(Picture-in-Picture)$

    float = yes
    pin = yes
    move = 100%-460 100%-320
    size = 420 236
}

windowrule {
    name = pip-firefox
    match:class = ^(firefox)$
    match:title = ^(Picture-in-Picture)$

    float = yes
    pin = yes
    move = 100%-460 100%-320
    size = 420 236
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
