# #######################################################################################
# HYPRLAND CONFIG ENTRYPOINT.
# MODULES LIVE IN ~/.config/hypr/conf/
# #######################################################################################

source = ~/.config/hypr/conf/variables.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/theme.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/rules.conf
