[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="JetBrainsMono Nerd Font Mono"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="0"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/opencode-wallpaper.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.4"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#d8dee9"
DateTextColor="#d8dee9"
TimeTextColor="#e5e9f0"

FormBackgroundColor="#1e212700"
BackgroundColor="#1e2127"
DimBackgroundColor="#1e2127"

LoginFieldBackgroundColor="#242933"
PasswordFieldBackgroundColor="#242933"
LoginFieldTextColor="#d8dee9"
PasswordFieldTextColor="#d8dee9"
UserIconColor="#d8dee9"
PasswordIconColor="#d8dee9"

PlaceholderTextColor="#a3b1c6"
WarningColor="#bf616a"

LoginButtonTextColor="#eceff4"
LoginButtonBackgroundColor="#3b4252"
SystemButtonsIconsColor="#d8dee9"
SessionButtonTextColor="#d8dee9"
VirtualKeyboardButtonTextColor="#d8dee9"

DropdownTextColor="#d8dee9"
DropdownSelectedBackgroundColor="#3b4252"
DropdownBackgroundColor="#242933"

HighlightTextColor="#d8dee9"
HighlightBackgroundColor="#242933"
HighlightBorderColor="#4c566a"

HoverUserIconColor="#81a1c1"
HoverPasswordIconColor="#81a1c1"
HoverSystemButtonsIconsColor="#81a1c1"
HoverSessionButtonTextColor="#81a1c1"
HoverVirtualKeyboardButtonTextColor="#81a1c1"

PartialBlur="true"
FullBlur=""
BlurMax="64"
Blur="1.6"

HaveFormBackground="false"
FormPosition="right"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername="username"
TranslatePlaceholderPassword="password"
TranslateLogin="login"
TranslateLoginFailedWarning="authentication failed"
TranslateCapslockWarning="caps lock"
TranslateSuspend="suspend"
TranslateHibernate="hibernate"
TranslateReboot="reboot"
TranslateShutdown="shutdown"
TranslateSessionSelection="session"
TranslateVirtualKeyboardButtonOn="keyboard"
TranslateVirtualKeyboardButtonOff="keyboard"
