[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="JetBrainsMono Nerd Font Mono"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="0"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/opencode-wallpaper.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.28"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#d8dee9"
DateTextColor="#81a1c1"
TimeTextColor="#d8dee9"

FormBackgroundColor="#2e3440dd"
BackgroundColor="#2e3440"
DimBackgroundColor="#2e3440"

LoginFieldBackgroundColor="#3b4252"
PasswordFieldBackgroundColor="#3b4252"
LoginFieldTextColor="#d8dee9"
PasswordFieldTextColor="#d8dee9"
UserIconColor="#d8dee9"
PasswordIconColor="#d8dee9"

PlaceholderTextColor="#81a1c1"
WarningColor="#bf616a"

LoginButtonTextColor="#2e3440"
LoginButtonBackgroundColor="#88c0d0"
SystemButtonsIconsColor="#d8dee9"
SessionButtonTextColor="#d8dee9"
VirtualKeyboardButtonTextColor="#d8dee9"

DropdownTextColor="#d8dee9"
DropdownSelectedBackgroundColor="#4c566a"
DropdownBackgroundColor="#2e3440"

HighlightTextColor="#d8dee9"
HighlightBackgroundColor="#4c566a"
HighlightBorderColor="#88c0d0"

HoverUserIconColor="#88c0d0"
HoverPasswordIconColor="#88c0d0"
HoverSystemButtonsIconsColor="#88c0d0"
HoverSessionButtonTextColor="#88c0d0"
HoverVirtualKeyboardButtonTextColor="#88c0d0"

PartialBlur="true"
FullBlur=""
BlurMax="64"
Blur="1.6"

HaveFormBackground="false"
FormPosition="center"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername="username"
TranslatePlaceholderPassword="password"
TranslateLogin="login"
TranslateLoginFailedWarning="authentication failed"
TranslateCapslockWarning="caps lock"
TranslateSuspend="suspend"
TranslateHibernate="hibernate"
TranslateReboot="reboot"
TranslateShutdown="shutdown"
TranslateSessionSelection="session"
TranslateVirtualKeyboardButtonOn="keyboard"
TranslateVirtualKeyboardButtonOff="keyboard"
